nec2++: nec_radiation_pattern Class Reference
nec_radiation_pattern Class Reference
Public Member Functions
nec_radiation_pattern (int in_n_theta, int in_n_phi, nec_float in_theta_start, nec_float in_phi_start, nec_float in_delta_theta, nec_float in_delta_phi, nec_float in_range, nec_ground &in_ground, int in_ifar, nec_float in_wavelength, nec_float pinr, nec_float pnlr, int in_rp_output_format, int in_rp_normalization, int in_rp_ipd, int in_rp_power_average, nec_float in_gnor, c_plot_card &in_plot_card)
virtual void write_to_file (ostream &os) override
virtual enum nec_result_type get_result_type () override
void analyze (nec_context *in_context)
Generate the data for the radiation pattern.
void write_gain_normalization ()
real_matrix get_gain ()
real_array get_gain_vert ()
real_array get_gain_horiz ()
real_array get_gain_tot ()
real_array get_pol_axial_ratio ()
nec_float get_pol_axial_ratio (int theta_index, int phi_index) const
Get the polarization axial ratio.
real_array get_pol_tilt ()
int_array get_pol_sense_index ()
int get_pol_sense (int theta_index, int phi_index) const
Get the polarization sense.
nec_float get_etheta_magnitude (int theta_index, int phi_index)
Get the magnitude of E(THETA)
nec_float get_etheta_phase (int theta_index, int phi_index)
Get the phase (in degrees) of E(THETA)
complex_array get_e_theta ()
Return a complex array for the electric field E(THETA)
nec_float get_ephi_magnitude (int theta_index, int phi_index)
Get the magnitude of E(PHI)
nec_float get_ephi_phase (int theta_index, int phi_index)
Get the phase (in degrees) of E(PHI)
complex_array get_e_phi ()
Return a complex array for the electric field E(PHI)
complex_array get_e_r ()
nec_float get_normalization_factor ()
nec_float get_average_power_gain ()
nec_float get_average_power_solid_angle ()
nec_ground get_ground ()
nec_float get_range ()
nec_float get_wavelength ()
real_array get_theta_angles () const
nec_float get_delta_theta ()
nec_float get_theta_start ()
real_array get_phi_angles () const
nec_float get_delta_phi ()
nec_float get_phi_start ()
int get_ifar ()
int get_rp_normalization ()
int get_rp_output_format ()
int get_rp_power_average ()
int get_rp_ipd ()
nec_float get_maximum_gain_db ()
nec_float get_gain_max () const
nec_float get_gain_min () const
nec_float get_gain_mean () const
nec_float get_gain_sd () const
nec_float get_gain_rhcp_max () const
nec_float get_gain_rhcp_min () const
nec_float get_gain_rhcp_mean () const
nec_float get_gain_rhcp_sd () const
nec_float get_gain_lhcp_max () const
nec_float get_gain_lhcp_min () const
nec_float get_gain_lhcp_mean () const
nec_float get_gain_lhcp_sd () const
nec_float get_theta (int theta_index) const
Get the theta angle corresponding to the theta_index.
int get_ntheta () const
Get the number of theta angles.
nec_float get_phi (int phi_index) const
Get the phi angle corresponding to the phi_index.
int get_nphi () const
Get the number of phi angles.
nec_float get_power_gain (int theta_index, int phi_index) const
Get a total power gain from the radiation pattern.
nec_float get_power_gain_vert (int theta_index, int phi_index) const
Get a power gain (vertical) from the radiation pattern.
nec_float get_power_gain_horiz (int theta_index, int phi_index) const
Get a power gain (horizontal) from the radiation pattern.
nec_float get_power_gain_tot (int theta_index, int phi_index) const
Get a power gain (total dBi) from the radiation pattern.
nec_float get_power_gain_rhcp (int theta_index, int phi_index) const
Get the power gain if the antenna were receiving RHCP signals.
nec_float get_power_gain_lhcp (int theta_index, int phi_index) const
Get the power gain if the antenna were receiving LHCP signals.
Public Member Functions inherited from nec_base_result
bool write_file () const
void set_write_file (bool f)
void set_frequency (nec_float f)
nec_float get_frequency ()
void set_result_format (enum RESULT_FORMAT f)
Additional Inherited Members
Protected Attributes inherited from nec_base_result
enum RESULT_FORMAT _result_format
Detailed Description
Examples
test_cpp.cpp.
Member Function Documentation
get_phi_angles()
real_array nec_radiation_pattern::get_phi_angles () const inline
Access the phi angles
References get_phi().
get_pol_sense()
int nec_radiation_pattern::get_pol_sense (int theta_index, int phi_index) const inline
Get the polarization sense.
Returns
enum polarization_sense POL_LINEAR, POL_RIGHT, POL_LEFT
Referenced by get_power_gain_lhcp(), and get_power_gain_rhcp().
get_result_type()
virtual enum nec_result_type nec_radiation_pattern::get_result_type () inline override virtual
Implements nec_base_result.
get_theta_angles()
real_array nec_radiation_pattern::get_theta_angles () const inline
Access the theta angles
References get_theta().
write_to_file()
virtual void nec_radiation_pattern::write_to_file (ostream & os) inline override virtual
Implements nec_base_result.
The documentation for this class was generated from the following files:
nec_radiation_pattern.h
nec_radiation_pattern.cpp