nec2++: nec_results Class Reference
nec_results Class Reference
#include <nec_results.h>
Public Member Functions
void add (nec_base_result *br)
nec_base_result * get_result (const long index, const enum nec_result_type result_type)
Get the nth result that matches the specified result type.
nec_norm_rx_pattern * get_norm_rx_pattern (const long index)
Get normalized receiving pattern results.
nec_radiation_pattern * get_radiation_pattern (const long index)
Get radiation pattern results.
nec_antenna_input * get_antenna_input (const long index)
Get antenna input parameter results.
nec_structure_excitation * get_structure_excitation (const long index)
Get structure excitation results.
nec_near_field_pattern * get_near_field_pattern (const long index)
Get near field pattern results.
nec_structure_currents * get_structure_currents (const long index)
Get structure currents results.
void write (ostream &os)
Public Attributes
enum RESULT_FORMAT m_result_format
Detailed Description
Stores a whole lot of nec_result objects. This class is effectively a database of the simulation results.
Usage
nec_antenna_input* ai = new nec_antenna_input(); s_results.add(ai); ai->set_intput(tag, segment, voltage, current, impedance, admittance, power); ai->set_intput(tag, segment, voltage, current, impedance, admittance, power); ai->set_intput(tag, segment, voltage, current, impedance, admittance, power);
Member Function Documentation
get_antenna_input()
nec_antenna_input * nec_results::get_antenna_input (const long index) inline
Get antenna input parameter results.
Parameters
index The zero-based index for the antenna input.
Returns
NULL if the result does not exist.
Note
You must NOT delete the nec_antenna_input object when finished with it.
References get_result().
Referenced by nec_context::get_input_parameters().
get_near_field_pattern()
nec_near_field_pattern * nec_results::get_near_field_pattern (const long index) inline
Get near field pattern results.
Parameters
index The zero-based index for the nec_structure_excitation.
Returns
NULL if the result does not exist.
Note
You must NOT delete the nec_structure_excitation object when finished with it.
References get_result().
Referenced by nec_context::get_near_field_pattern().
get_norm_rx_pattern()
nec_norm_rx_pattern * nec_results::get_norm_rx_pattern (const long index) inline
Get normalized receiving pattern results.
Parameters
index The zero-based index for the normalized receiving pattern.
Returns
NULL if the result does not exist.
Note
You must NOT delete the nec_norm_rx_pattern object when finished with it.
References get_result().
Referenced by nec_context::get_norm_rx_pattern().
get_radiation_pattern()
nec_radiation_pattern * nec_results::get_radiation_pattern (const long index) inline
Get radiation pattern results.
Parameters
index The zero-based index for the radiation pattern.
Returns
NULL if the result does not exist.
Note
You must NOT delete the nec_radiation_pattern object when finished with it.
References get_result().
Referenced by nec_context::get_radiation_pattern().
get_result()
nec_base_result * nec_results::get_result (const long index, const enum nec_result_type result_type) inline
Get the nth result that matches the specified result type.
Parameters
index The zero-based index for the result
result_type The requested result type
Returns
NULL if the result does not exist.
Note
You must NOT delete the nec_norm_rx_pattern object when finished with it.
Referenced by get_antenna_input(), get_near_field_pattern(), get_norm_rx_pattern(), get_radiation_pattern(), get_structure_currents(), and get_structure_excitation().
get_structure_currents()
nec_structure_currents * nec_results::get_structure_currents (const long index) inline
Get structure currents results.
Parameters
index The zero-based index for the nec_structure_excitation.
Returns
NULL if the result does not exist.
Note
You must NOT delete the nec_structure_excitation object when finished with it.
References get_result().
Referenced by nec_context::get_structure_currents().
get_structure_excitation()
nec_structure_excitation * nec_results::get_structure_excitation (const long index) inline
Get structure excitation results.
Parameters
index The zero-based index for the nec_structure_excitation.
Returns
NULL if the result does not exist.
Note
You must NOT delete the nec_structure_excitation object when finished with it.
References get_result().
Referenced by nec_context::get_structure_excitation().
The documentation for this class was generated from the following file:
nec_results.h