
LIBTOOLIZE=libtoolize

UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)
	LIBTOOLIZE=glibtoolize
endif

default: all

all:
	$(LIBTOOLIZE) --force --copy
	aclocal
	autoheader
	automake --add-missing
	autoconf

