.TH nec2++ 1 "May 3, 2015" "NEC2++"

.SH NAME
nec2++ \- NEC2 (Numerical Electromagnetics Code) is software for modelling
antennas using the Method of Moments.

.SH SYNOPSIS
.B nec2++
.br

.SH DESCRIPTION
.B nec2++
performs antennas modelling using the Method of Moments.

.SH OPTIONS
.B
.IP -i<input-file-name>
Set the input file-name instead of standard input
.B
.IP -o<output-file-name>]
Set the output file-name instead of standard output
.B
.IP -g
Print maximum gain to stdout.
.B
.IP -b
Perform NEC++ Benchmark.
.B
.IP -s
Print results to standard output.
.B
.IP -c
Print results in comma-separated-value (CSV) format, this options is used in conjunction with (-s) above.
.B
.IP -h 
Print this usage information and exit.
.B
.IP -v
Print nec2++ version number and exit.

.SH AUTHOR
The C++ port started and completed by Tim Molteno <tim@physics.otago.ac.nz>
The Ruby and Python C-style API work is done by Tim Molteno<tim@physics.otago.ac.nz>
The Python C++ api is done by Remi Sassolas<uptheiron@wanadoo.fr>
This work could not have been done without the tremendous effort put into the C 
port by Neoklis Kyriazis.
