.TH nec2diff 1 "Nov 3, 2009" "NEC2++"

.SH NAME
nec2diff \- NEC2 (Numerical Electromagnetics Code) is software for modelling
antennas using the Method of Moments.

.SH SYNOPSIS
.B nec2diff

.SH DESCRIPTION
.B nec2diff
evaluates differences between 2 result files given as parameters.

.SH AUTHOR
nec2diff was written by Tim Molteno <tim@physics.otago.ac.nz>
